/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as PlanoContasRouteImport } from './routes/plano-contas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as FluxoCaixaRouteImport } from './routes/fluxo-caixa'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DreRouteImport } from './routes/dre'
import { Route as DeducoesRouteImport } from './routes/deducoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CmvRouteImport } from './routes/cmv'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoContasRoute = PlanoContasRouteImport.update({
  id: '/plano-contas',
  path: '/plano-contas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoCaixaRoute = FluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DreRoute = DreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const DeducoesRoute = DeducoesRouteImport.update({
  id: '/deducoes',
  path: '/deducoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CmvRoute = CmvRouteImport.update({
  id: '/cmv',
  path: '/cmv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cmv': typeof CmvRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/deducoes': typeof DeducoesRoute
  '/dre': typeof DreRoute
  '/empresa': typeof EmpresaRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/funcionarios': typeof FuncionariosRoute
  '/gastos': typeof GastosRoute
  '/login': typeof LoginRoute
  '/plano-contas': typeof PlanoContasRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cmv': typeof CmvRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/deducoes': typeof DeducoesRoute
  '/dre': typeof DreRoute
  '/empresa': typeof EmpresaRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/funcionarios': typeof FuncionariosRoute
  '/gastos': typeof GastosRoute
  '/login': typeof LoginRoute
  '/plano-contas': typeof PlanoContasRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cmv': typeof CmvRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/deducoes': typeof DeducoesRoute
  '/dre': typeof DreRoute
  '/empresa': typeof EmpresaRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/funcionarios': typeof FuncionariosRoute
  '/gastos': typeof GastosRoute
  '/login': typeof LoginRoute
  '/plano-contas': typeof PlanoContasRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cmv'
    | '/configuracoes'
    | '/deducoes'
    | '/dre'
    | '/empresa'
    | '/fluxo-caixa'
    | '/funcionarios'
    | '/gastos'
    | '/login'
    | '/plano-contas'
    | '/receitas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cmv'
    | '/configuracoes'
    | '/deducoes'
    | '/dre'
    | '/empresa'
    | '/fluxo-caixa'
    | '/funcionarios'
    | '/gastos'
    | '/login'
    | '/plano-contas'
    | '/receitas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cmv'
    | '/configuracoes'
    | '/deducoes'
    | '/dre'
    | '/empresa'
    | '/fluxo-caixa'
    | '/funcionarios'
    | '/gastos'
    | '/login'
    | '/plano-contas'
    | '/receitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CmvRoute: typeof CmvRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DeducoesRoute: typeof DeducoesRoute
  DreRoute: typeof DreRoute
  EmpresaRoute: typeof EmpresaRoute
  FluxoCaixaRoute: typeof FluxoCaixaRoute
  FuncionariosRoute: typeof FuncionariosRoute
  GastosRoute: typeof GastosRoute
  LoginRoute: typeof LoginRoute
  PlanoContasRoute: typeof PlanoContasRoute
  ReceitasRoute: typeof ReceitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-contas': {
      id: '/plano-contas'
      path: '/plano-contas'
      fullPath: '/plano-contas'
      preLoaderRoute: typeof PlanoContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-caixa': {
      id: '/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof FluxoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dre': {
      id: '/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof DreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deducoes': {
      id: '/deducoes'
      path: '/deducoes'
      fullPath: '/deducoes'
      preLoaderRoute: typeof DeducoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmv': {
      id: '/cmv'
      path: '/cmv'
      fullPath: '/cmv'
      preLoaderRoute: typeof CmvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CmvRoute: CmvRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DeducoesRoute: DeducoesRoute,
  DreRoute: DreRoute,
  EmpresaRoute: EmpresaRoute,
  FluxoCaixaRoute: FluxoCaixaRoute,
  FuncionariosRoute: FuncionariosRoute,
  GastosRoute: GastosRoute,
  LoginRoute: LoginRoute,
  PlanoContasRoute: PlanoContasRoute,
  ReceitasRoute: ReceitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
